/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jpmm;

import java.util.Scanner;

import java.util.ArrayList;

public class App {

    public static void test() {

    }

    public static void main(String[] args) {

        Scanner scanner = new Scanner(System.in);
        ArrayList<AccountModel> returnedAccounts;
        AccountModel correctAccount;
        String userInput = "";
        DatabaseDao Dao = new DatabaseDao();

        System.out.println("Enter the Name of The Account Or Enter A Command: ");

        if (scanner.hasNextLine()) {
            userInput = scanner.nextLine();
        }

        if (userInput == "") {
            System.exit(-1);
        }

        // handles commands
        if (userInput.startsWith(".")) {
            handleCommands(userInput);
        } else {
            returnedAccounts = Dao.getLikeAccounts(userInput);
            correctAccount = getCorrectAccount(returnedAccounts);
            printAccount(correctAccount);
        }

        MyScannerWrapper.close();
        scanner.close();
    }

    public static AccountModel getCorrectAccount(ArrayList<AccountModel> accounts) {

        Scanner scanner = new Scanner(System.in);
        int size = accounts.size();
        int userInput = 1;
        System.out.println("Which Account:");

        String output;

        for (int i = 0; i < size; i++) {
            output = String.format("%d: %s", i + 1, accounts.get(i).getAccount());
            System.out.println(output);
        }

        // subtract 1 to take be in sync with the menu
        if (scanner.hasNextInt()) {
            userInput = scanner.nextInt();
            userInput--;
        }

        while (userInput < 0 || userInput > (size - 1)) {
            System.out.println("INVALID INPUT, TRY OPTION");
            if (scanner.hasNextInt()) {
                userInput = scanner.nextInt();
                userInput--;
            }
        }

        MyUtil.clearConsole();
        scanner.close();
        return accounts.get(userInput);
    }

    public static void printAccount(AccountModel accountModel) {

        String output;
        output = String.format("Account: %s \nUsername: %s \nPassword: %s \n", accountModel.getAccount(),
                accountModel.getUsername(), accountModel.getPassword());
        System.out.print(output);

    }

    public static void handleCommands(String userInput) {

        // remove the '.' from the input to check the input
        // makes upper case to look nice in code IDK
        userInput = userInput.substring(1).toUpperCase();

        switch (userInput) {
            case "A":
                addAccount();
                break;
            case "D":
                break;
            default:
                break;
        }
    }

    public static void addAccount() {

        DatabaseDao Dao = new DatabaseDao();
        String accountName = "";
        String userName = "";
        int passLen = -1;

        System.out.println("Enter The Name of The Account You Want To Add: ");
        accountName = MyScannerWrapper.getStringInput();

        System.out.println("Enter The Username/Email For The Account: ");
        userName = MyScannerWrapper.getStringInput();

        System.out.println("Enter The Length Of Password To Be Generated: ");
        Dao.addAccount(accountName, userName, passLen);
    }
}
