/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jpmm;

public class App {

    public static void main(String[] args) {

        DatabaseDao DD = new DatabaseDao();

        DD.getAllAccounts();

    }
}
